language: ruby
rvm: 2.6.5
before_install:
- sudo apt-get update
- gem update --system
- gem install bundler:1.17.3
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
- sleep 1
script:
- bundle install
- bundle exec rspec
- ruby request.rb
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
services:
  - postgresql
addons:
  postgresql: 11
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
    - PGPORT=5433
    - PGDATABASE=fcg
    - PGUSER=postgres
    - PGHOST=localhost
