language: ruby
rvm:
  - 2.6.5

before_install:
  - sudo apt-get update
  - gem update --system
  - gem install bundler:1.17.3
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
script:
  - bundle install
  - bundle exec rails webpacker:compile
  - bundle exec rails spec
  # - bundle exec rake $TASKS
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
services:
  - postgresql
addons:
  postgresql: "11.6"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
    - PGPORT=5433
    - PGUSER=postgres
    - PGHOST=localhost
    - CC_TEST_REPORTER_ID=f22ce1fc771ebc76e70b3254fe02703c8c5cdbd142e22c304f914bf707939459
    - CODECOV_TOKEN=9c5ef3b9-cca0-4f8a-985e-921864d9750d
    - CF_RUN_PERM_SPECS=false
  matrix:
    - COVERAGE=true DB=travis_ci_test TASKS=spec:all
    - TASKS=rubocop
