language: ruby
rvm: 2.6.5
before_install:
- sudo apt-get update
- gem update --system
- gem install bundler:1.17.3
- sudo apt-get --yes remove postgresql\*
- sudo apt-get install -y postgresql-11 postgresql-client-11
- sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
- sudo service postgresql restart 11
script:
- bundle install
- RAILS_ENV=test ./bin/rails webpacker:compile
- bundle exec rspec
- ruby request.rb
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - cp config/database.yml.travis config/database.yml
services:
  - postgresql
addons:
  postgresql: "11.6"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
    - PGPORT=5433
    - PGUSER=postgres
    - PGHOST=localhost
