default: &default
  adapter: postgresql
  encoding: unicode
  port: 5433
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: netshowme_dev_test_development

test:
  <<: *default
  database: netshowme_dev_test_test

production:
  <<: *default
  database: netshowme_dev_test_production
  username: netshowme_dev_test
  password: <%= ENV['NETSHOWME_DEV_TEST_DATABASE_PASSWORD'] %>
